### PR TITLE
Drop Navigation Icon

### PR DESCRIPTION
**Pull request by lkiesow**
This patch drops the small navigation icon in favor of the project's
name.

### CODE REVIEW

**Comment by shaardie** [comment]
The text is not aligned with the burger menu in the mobile version, see 
image

**Comment by shaardie** [comment]
Honestly, it still does not look aligned. I use the `responsive design mode` from Firefox and the iPhone X:
image

**Comment by lkiesow** [comment]
I guess the question is where do you want this to be aligned? I've now aligned the baseline of the text with the bottom of the menu icon. If that does not work for you, please explain what you like to have aligned.

**Comment by shaardie** [comment]
Fair enough. I would align them horizontally to the center of the font, like this

Screenshot from 2020-02-17 09-58-32

**Comment by shaardie** [comment]
I have just looked at your current solution and it looks good to me. I will merge it.

**Pull request merged**
