### PR TITLE
Use FontAwesome Icons

### PR DESCRIPTION
**Pull request by lkiesow**
This patch introduces FontAwesome icons to add a visual representation
for certain links and buttons.

### CODE REVIEW

**Review by shaardie — COMMENTED** [review]
@lkiesow  Looks good so far. Just one question. Why did you choose this *graph* icon for the API? Most images I find when searching for API icons are either gears or clouds.

**Comment by lkiesow** [comment]
Because our API is meant to connect things.
Do you have a [better suggestion](https://fontawesome.com/icons?d=gallery&m=free)?
A [single gear](https://fontawesome.com/icons/cog?style=solid) is what I would associate with settings.
Maybe [multiple, engaged gears](https://fontawesome.com/icons/cogs?style=solid) would be an alternative?
I wouldn't have any [cloud icons](https://fontawesome.com/icons?d=gallery&q=cloud&m=free) which I would associate with APIs.

**Comment by shaardie** [comment]
I agree. A single gear does not fit and the clouds in this font do not look like API. 

Maybe we can go with the multiple gears or maybe with some kind of[globe](https://fontawesome.com/icons?d=gallery&q=globe&m=free).

If you would like to stick to the graph icon, I am honestly as happy as if you change to some of the proposed one. So decide what you would like to use, give me a ping and I am happy to merge this.

**Comment by lkiesow** [comment]
I've played a bit with the icons (also slightly increasing the padding between icons and text). What do you think?

Screenshot from 2019-11-16 13-11-13
Screenshot from 2019-11-16 13-11-46
Screenshot from 2019-11-16 13-11-33

**Comment by TylerBird** [comment]
> I've played a bit with the icons (also slightly increasing the padding between icons and text). What do you think?
> 
> […]

I would choose the 1st one. It describes that it is a Web-API the most.

**Comment by benszau** [comment]
> 
> 
> I've played a bit with the icons (also slightly increasing the padding between icons and text). What do you think?
> 
I like the second combination since it shows multiple connections to 'our API'.

**Comment by lkiesow** [comment]
Running with the globe now.

**Review by shaardie — APPROVED** [review]

**Pull request merged**
